// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kol2.Data;

#nullable disable

namespace kol2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250604165301_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Available_ProgramPurchase_History", b =>
                {
                    b.Property<int>("AvailableProgramsAvailableProgramId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseHistoriesAvailableProgramId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseHistoriesCustomerId")
                        .HasColumnType("int");

                    b.HasKey("AvailableProgramsAvailableProgramId", "PurchaseHistoriesAvailableProgramId", "PurchaseHistoriesCustomerId");

                    b.HasIndex("PurchaseHistoriesAvailableProgramId", "PurchaseHistoriesCustomerId");

                    b.ToTable("Available_ProgramPurchase_History");
                });

            modelBuilder.Entity("kol2.Models.Available_Program", b =>
                {
                    b.Property<int>("AvailableProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailableProgramId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("WashingMachineId")
                        .HasColumnType("int");

                    b.HasKey("AvailableProgramId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("WashingMachineId");

                    b.ToTable("Available_Program", (string)null);

                    b.HasData(
                        new
                        {
                            AvailableProgramId = 1,
                            Price = 20m,
                            ProgramId = 1,
                            WashingMachineId = 2
                        },
                        new
                        {
                            AvailableProgramId = 2,
                            Price = 40m,
                            ProgramId = 3,
                            WashingMachineId = 1
                        });
                });

            modelBuilder.Entity("kol2.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Jane",
                            LastName = "Doe",
                            PhoneNumber = "987654321"
                        });
                });

            modelBuilder.Entity("kol2.Models.ProgramEntity", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TemperatureCelsius")
                        .HasColumnType("int");

                    b.HasKey("ProgramId");

                    b.ToTable("Program", (string)null);

                    b.HasData(
                        new
                        {
                            ProgramId = 1,
                            DurationMinutes = 60,
                            Name = "Program1",
                            TemperatureCelsius = 60
                        },
                        new
                        {
                            ProgramId = 2,
                            DurationMinutes = 40,
                            Name = "Program2",
                            TemperatureCelsius = 30
                        },
                        new
                        {
                            ProgramId = 3,
                            DurationMinutes = 30,
                            Name = "Program3",
                            TemperatureCelsius = 20
                        });
                });

            modelBuilder.Entity("kol2.Models.Purchase_History", b =>
                {
                    b.Property<int>("AvailableProgramId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("AvailableProgramId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Purchase_History", (string)null);

                    b.HasData(
                        new
                        {
                            AvailableProgramId = 1,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            AvailableProgramId = 2,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2
                        });
                });

            modelBuilder.Entity("kol2.Models.Washing_Machine", b =>
                {
                    b.Property<int>("WashingMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WashingMachineId"));

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WashingMachineId");

                    b.ToTable("Washing_Machine", (string)null);

                    b.HasData(
                        new
                        {
                            WashingMachineId = 1,
                            MaxWeight = 20m,
                            SerialNumber = "abcd"
                        },
                        new
                        {
                            WashingMachineId = 2,
                            MaxWeight = 30m,
                            SerialNumber = "dafa"
                        },
                        new
                        {
                            WashingMachineId = 3,
                            MaxWeight = 40m,
                            SerialNumber = "iorem"
                        });
                });

            modelBuilder.Entity("Available_ProgramPurchase_History", b =>
                {
                    b.HasOne("kol2.Models.Available_Program", null)
                        .WithMany()
                        .HasForeignKey("AvailableProgramsAvailableProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kol2.Models.Purchase_History", null)
                        .WithMany()
                        .HasForeignKey("PurchaseHistoriesAvailableProgramId", "PurchaseHistoriesCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("kol2.Models.Available_Program", b =>
                {
                    b.HasOne("kol2.Models.ProgramEntity", "Program")
                        .WithMany("AvailablePrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kol2.Models.Washing_Machine", "Washing_Machine")
                        .WithMany("AvailablePrograms")
                        .HasForeignKey("WashingMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Washing_Machine");
                });

            modelBuilder.Entity("kol2.Models.Purchase_History", b =>
                {
                    b.HasOne("kol2.Models.Customer", null)
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("kol2.Models.Customer", b =>
                {
                    b.Navigation("PurchaseHistories");
                });

            modelBuilder.Entity("kol2.Models.ProgramEntity", b =>
                {
                    b.Navigation("AvailablePrograms");
                });

            modelBuilder.Entity("kol2.Models.Washing_Machine", b =>
                {
                    b.Navigation("AvailablePrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
